import React, { useMemo, useState } from "react";

const HOTEL = {
  name: "The Hotel Senator",
  address: "243 21st Street East, Saskatoon, SK S7K 0B7",
  phone: "306-244-6141",
  email: "info@hotelsenator.ca",
  bookingUrl: "https://www.hotelsenator.ca/booking-page",
  contactUrl: "https://www.hotelsenator.ca/contact",
};

const BREWERY = {
  name: "21st Street Brewery",
  phone: "306-374-7468",
  websiteUrl: "https://www.21ststreetbrewery.ca/",
  menuUrl: "https://www.21ststreetbrewery.ca/menus",
  reservationsUrl: "https://www.21ststreetbrewery.ca/reservations",
  hours: "Friday and Saturday, 4pm to midnight. Private bookings welcome on other days.",
};

const WINSTONS = {
  name: "Winston's English Pub",
  websiteUrl: "https://www.winstonspub.ca/",
};

const FLANAGANS = {
  name: "Flanagan's Steakhouse",
  phone: "306-244-8555",
  reservationUrl: "https://www.flanaganssteakhouse.ca/reservations",
  menuUrl: "https://www.flanaganssteakhouse.ca/menus?menu=menu",
};

const IMAGES = {
  hotel: {
    src: "https://www.saskatoon.ca/sites/default/files/2024-04/Flanagan-Senator%20Hotel3_2010_aa.JPG",
    alt: "Historic Hotel Senator exterior in downtown Saskatoon",
    title: "Hotel Senator",
    eyebrow: "Downtown Saskatoon",
    caption: "A heritage landmark with rooms, dining, pub nights, private rooms, and local history under one roof.",
  },
  hotelFacade: { src: "https://www.saskatoon.ca/sites/default/files/images/Heritage/Senator%20Hotel.JPG", alt: "Hotel Senator heritage exterior and entrance canopy" },
  hotelCorner: { src: "https://dtnyxe.ca/wp-content/uploads/2023/08/Winstons-.jpg", alt: "Hotel Senator corner exterior with Winston's Pub signage" },
  hotelDining: { src: "https://www.tourismsaskatchewan.com/_next/image?q=100&url=https%3A%2F%2Ftsaskblobstorage.blob.core.windows.net%2Fics%2FSenatorH_04SC28577.jpg&w=1920", alt: "Warm wood interior dining and pub space at Hotel Senator" },
  vintage: { src: "https://www.tourismsaskatchewan.com/_next/image?q=100&url=https%3A%2F%2Ftsaskblobstorage.blob.core.windows.net%2Fics%2FTheHotelSenator_0131585.jpg&w=1920", alt: "Historic Hotel Senator hospitality space" },
  winstons: { src: "https://www.tourismsaskatchewan.com/_next/image?dpl=dpl_8qDfneeLncPxjGkDXGRYQgiER6Xp&q=100&url=https%3A%2F%2Ftsaskblobstorage.blob.core.windows.net%2Fics%2Fwinstons_pub_3_220250227021034.jpg&w=1920", alt: "Warm wood interior of Winston's English Pub", title: "Winston's Pub", eyebrow: "Classic English Pub", caption: "Dark wood, proper pints, hearty pub classics, and a warm English-pub atmosphere inside the Hotel Senator." },
  brewery: { src: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,h_600,q_75,w_800/v1/clients/saskatoon/Discover_Saskatoon_Walking_Brewery_Tour_21st_Street_Brewery_Casey_Murray_8c218ff9-02b0-45dd-a100-eb5dd8fcfabd.jpg", alt: "21st Street Brewery taproom", title: "21st Street Brewery", eyebrow: "Downtown Saskatoon Brewery", caption: "A small-batch brewery below Winston's English Pub & Grill, built around local brews, taproom nights, and private bookings." },
  flanagans: { src: "https://static.wixstatic.com/media/2b560f_a0125ad63ab24ec0a194d13e1386ea44~mv2.jpg/v1/fill/w_980%2Ch_653%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/2b560f_a0125ad63ab24ec0a194d13e1386ea44~mv2.jpg", alt: "Flanagan's dining room", title: "Flanagan's Steakhouse", eyebrow: "Classic Tableside Dining", caption: "Old-world steakhouse dining, wine, and tableside service in the historic Hotel Senator." },
  flanagansRoom: { src: "https://static.wixstatic.com/media/2b560f_c23cae443c35431cae9922043393fe82~mv2.jpg/v1/fill/w_848%2Ch_565%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/2b560f_c23cae443c35431cae9922043393fe82~mv2.jpg", alt: "Flanagan's private dining" },
  flanagansTableside: { src: "https://static.wixstatic.com/media/2b560f_6dc155571d424716bae1f885103062d8~mv2.jpg/v1/fill/w_490%2Ch_327%2Cal_c%2Cq_80%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/2b560f_6dc155571d424716bae1f885103062d8~mv2.jpg", alt: "Tableside service" },
  flanagansWine: { src: "https://static.wixstatic.com/media/2b560f_1a67a2f9f618447ea3196c2372925642~mv2.jpg/v1/fill/w_729%2Ch_555%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/2b560f_1a67a2f9f618447ea3196c2372925642~mv2.jpg", alt: "Wine at Flanagan's" },
};

const hotelGallery = [
  ["Heritage Exterior", "Landmark facade", "hotelFacade", "Historic brick, arched windows, and the classic Senator entrance in downtown Saskatoon."],
  ["Downtown Corner", "21st Street East", "hotelCorner", "A walkable downtown address connecting the hotel, Winston's Pub, and on-site hospitality."],
  ["Senator Hospitality", "Dining & gathering", "vintage", "Classic interiors and warm hospitality spaces designed for memorable city-centre stays."],
  ["Pub & Dining Atmosphere", "Inside the hotel", "hotelDining", "Wood-lined dining, pub nights, private rooms, and destination food and beverage under one roof."],
];

const rooms = [
  ["Classic Boutique Rooms", "Heritage comfort", "Warm textures, practical work space, and downtown convenience for business or leisure stays."],
  ["Jacuzzi Suites", "Relaxed upgrade", "A more indulgent stay with room to unwind after dinner, a show, or a night out downtown."],
  ["Group & Event Stays", "Stay together", "Simple access to private dining, meeting space, restaurants, and central Saskatoon attractions."],
];

const dining = [
  ["Winston's Craft Beer Pub", "Pub & Grill", "winstons", "winstons", "A lively English pub for proper pints, comfort food, and a night out without leaving the hotel."],
  ["Flanagan's Steakhouse", "Classic steakhouse", "flanagans", "flanagans", "Casual upscale dining in a historic Edwardian setting, ideal for special evenings and private rooms."],
  ["21st Street Brewery", "Downtown brewery", "brewery", "brewery", "Small-batch local beer below Winston's English Pub & Grill, with taproom nights and private bookings."],
  ["Vintage Wine Bar", "Wine bar", "vintage", null, "A tucked-away spot for wine, conversation, and a more intimate evening downtown."],
];

const beers = ["Sunny Day IPA", "Cloud Burst New England IPA", "Uptown American Brown Ale", "Hopsicle IPA", "Black Market Stout", "Sweet Lea Blonde Ale"];
const pubMenu = ["Fish & Chips", "Bangers & Mash", "Pints, Cask Ale & Draught", "Sunday Roast & Supper Feel"];
const flanagansExperiences = [
  ["Steak Diane Tableside", "Signature service", "flanagansTableside", "A dramatic steakhouse moment with classic preparation, flame, and old-world presentation."],
  ["Private Dining", "Groups & occasions", "flanagansRoom", "A polished setting for romantic dinners, business meals, rehearsal dinners, and private events."],
  ["Wine & Cocktails", "Pairings", "flanagansWine", "Deep wine, classic cocktails, and an elevated pace that separates Flanagan's from casual dining."],
];

function phoneHref(phone) { return `tel:${phone.replace(/[^0-9]/g, "")}`; }
function cx(...classes) { return classes.filter(Boolean).join(" "); }
function Button({ href = "#", children, variant = "primary", onClick }) {
  return <a href={href} onClick={onClick} className={cx("inline-flex min-h-11 w-full items-center justify-center rounded-full px-5 py-3 text-sm font-semibold transition sm:w-auto", variant === "primary" ? "bg-amber-300 text-stone-950 hover:bg-amber-200" : "border border-white/25 bg-white/5 text-white hover:bg-white/10")}>{children}</a>;
}
function SectionLabel({ children }) { return <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-amber-300/40 bg-amber-100/70 px-4 py-2 text-xs font-semibold uppercase tracking-[0.22em] text-amber-900"><span className="h-1.5 w-1.5 rounded-full bg-amber-700" />{children}</div>; }
function IconBadge({ children }) { return <span className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-100 text-xs font-bold uppercase tracking-tight text-amber-900">{children}</span>; }
function PhotoHero({ image }) { return <div className="relative mx-auto aspect-[5/4] w-full max-w-md overflow-hidden rounded-[1.5rem] border border-white/20 bg-stone-900 shadow-2xl sm:aspect-[4/5]"><img src={image.src} alt={image.alt} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/25 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-4 sm:p-8"><div className="rounded-[1.25rem] border border-white/15 bg-white/10 p-4 text-white shadow-xl backdrop-blur sm:p-6"><p className="font-serif text-3xl leading-none sm:text-5xl">{image.title}</p><p className="mt-2 text-[11px] uppercase tracking-[0.22em] text-amber-100">{image.eyebrow}</p><p className="mt-3 text-xs leading-5 text-stone-100 sm:text-sm">{image.caption}</p></div></div></div>; }
function PhotoCard({ image, title, eyebrow, children }) { return <article className="overflow-hidden rounded-[1.5rem] border border-stone-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-44 overflow-hidden sm:h-48"><img src={image.src} alt={image.alt} className="h-full w-full object-cover transition duration-500 hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-stone-950/70 via-transparent to-transparent"/><div className="absolute bottom-4 left-4 right-4 text-white"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-100">{eyebrow}</p><h3 className="mt-1 font-serif text-2xl">{title}</h3></div></div><div className="p-6">{children}</div></article>; }

function Header({ page, navigate }) {
  const [open, setOpen] = useState(false);
  const go = (next, section) => (e) => { e.preventDefault(); setOpen(false); navigate(next, section); };
  const links = [["Hotel Home", "hotel", "top"], ["Winston's Pub", "winstons", "winstons-top"], ["Flanagan's", "flanagans", "flanagans-top"], ["21st Street Brewery", "brewery", "brewery-top"]];
  return <header className="fixed left-0 right-0 top-0 z-50 border-b border-white/20 bg-stone-950/95 text-white shadow-lg backdrop-blur-xl"><nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 lg:px-8 lg:py-4"><a href="#top" onClick={go("hotel", "top")} className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full border border-amber-200/40 bg-amber-100/10 font-serif text-lg text-amber-100">HS</div><div><p className="font-serif text-base leading-none sm:text-lg">Hotel Senator</p><p className="text-[10px] uppercase tracking-[0.18em] text-stone-300">Saskatoon</p></div></a><div className="hidden items-center gap-1 lg:flex">{links.map(([label,next,section]) => <a key={label} href={`#${section}`} onClick={go(next, section)} className={cx("rounded-full px-4 py-2 text-sm transition hover:bg-white/10", page === next ? "bg-white/10 text-white" : "text-stone-200")}>{label}</a>)}</div><div className="hidden items-center gap-3 lg:flex"><a href={phoneHref(HOTEL.phone)} className="text-sm text-stone-200 hover:text-white">{HOTEL.phone}</a><Button href={HOTEL.bookingUrl}>Book now</Button></div><button type="button" onClick={() => setOpen(!open)} className="rounded-full border border-white/20 p-2.5 lg:hidden" aria-label="Toggle menu">{open ? "X" : "☰"}</button></nav>{open && <div className="border-t border-white/10 bg-stone-950 px-5 py-4 lg:hidden"><div className="grid gap-2">{links.map(([label,next,section]) => <a key={label} href={`#${section}`} onClick={go(next, section)} className="rounded-xl px-3 py-3 text-stone-100 hover:bg-white/10">{label}</a>)}<Button href={HOTEL.bookingUrl}>Book now</Button></div></div>}</header>;
}

function HotelHome({ navigate }) {
  const go = (page, section) => (e) => { e.preventDefault(); navigate(page, section); };
  return <><section id="top" className="relative overflow-hidden bg-stone-950 pt-20 text-white sm:pt-24 lg:pt-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,rgba(251,191,36,0.22),transparent_30%)]"/><div className="relative mx-auto grid max-w-7xl items-center gap-8 px-4 py-10 sm:px-5 sm:py-14 lg:grid-cols-[1.08fr_0.92fr] lg:px-8 lg:py-24"><div><div className="mb-6 inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm text-amber-100 backdrop-blur">Boutique hotel in the heart of Downtown Saskatoon</div><h1 className="font-serif text-4xl leading-[0.98] tracking-tight sm:text-6xl lg:text-7xl">Historic stays, classic dining, and downtown nights.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-stone-200 sm:text-lg">{HOTEL.name} brings together heritage rooms, on-site restaurants, a craft beer pub, and walkable access to Saskatoon's city centre.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button href={HOTEL.bookingUrl}>Check availability</Button><Button href="#winstons-top" onClick={go("winstons", "winstons-top")} variant="outline">Visit Winston's Pub</Button><Button href="#flanagans-top" onClick={go("flanagans", "flanagans-top")} variant="outline">Reserve Flanagan's</Button><Button href="#brewery-top" onClick={go("brewery", "brewery-top")} variant="outline">Visit 21st Street Brewery</Button></div></div><PhotoHero image={IMAGES.hotel}/></div></section><Gallery/><Stay/><Dining navigate={navigate}/><Amenities/><Explore/><Contact/></>;
}
function Gallery() { return <section id="gallery" className="mx-auto max-w-7xl px-4 py-14 sm:px-5 sm:py-20 lg:px-8"><div className="mx-auto max-w-3xl text-center"><SectionLabel>Hotel Gallery</SectionLabel><h2 className="font-serif text-3xl leading-tight sm:text-5xl">See the historic Hotel Senator experience.</h2><p className="mt-4 text-base leading-7 text-stone-600 sm:text-lg">A visual look at the landmark exterior, downtown corner, dining atmosphere, and heritage hospitality that anchor the Senator experience.</p></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{hotelGallery.map(([title,eyebrow,key,copy]) => <PhotoCard key={title} image={IMAGES[key]} title={title} eyebrow={eyebrow}><p className="text-sm leading-6 text-stone-600">{copy}</p></PhotoCard>)}</div></section>; }
function Stay() { return <section id="stay" className="mx-auto max-w-7xl px-4 py-14 sm:px-5 sm:py-20 lg:px-8"><div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr]"><div><SectionLabel>Stay</SectionLabel><h2 className="font-serif text-3xl leading-tight sm:text-5xl">Rooms with historic warmth and modern essentials.</h2><p className="mt-4 max-w-xl text-base leading-7 text-stone-600 sm:text-lg">Designed for travellers who want a central location, character, and easy access to the city's restaurants, business district, and nightlife.</p></div><div className="grid gap-4 md:grid-cols-3">{rooms.map(([title,eyebrow,copy]) => <article key={title} className="rounded-[1.5rem] border border-stone-200 bg-white p-6 shadow-sm"><IconBadge>Room</IconBadge><p className="mt-5 text-sm font-semibold uppercase tracking-[0.18em] text-amber-800">{eyebrow}</p><h3 className="mt-3 font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{copy}</p></article>)}</div></div></section>; }
function Dining({ navigate }) { const go = (page, section) => (e) => { e.preventDefault(); navigate(page, section); }; return <section id="dining" className="bg-stone-100 py-14 sm:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="mx-auto max-w-3xl text-center"><SectionLabel>Dining</SectionLabel><h2 className="font-serif text-3xl leading-tight sm:text-5xl">Eat, drink, and gather without leaving the building.</h2><p className="mt-4 text-base leading-7 text-stone-600 sm:text-lg">From steakhouse evenings to craft beer and wine, the Senator is built for memorable nights downtown.</p></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{dining.map(([title,type,key,page,copy]) => { const card = <PhotoCard image={IMAGES[key]} title={title} eyebrow={type}><p className="text-sm leading-6 text-stone-600">{copy}</p><div className="mt-6 text-sm font-semibold text-stone-950">{page ? "Open page ->" : "Learn more ->"}</div></PhotoCard>; return page ? <a key={title} href={`#${page}-top`} onClick={go(page, `${page}-top`)}>{card}</a> : <a key={title} href="https://www.hotelsenator.ca/restaurants-and-brewery">{card}</a>; })}</div></div></section>; }
function Amenities() { return <section id="amenities" className="mx-auto max-w-7xl px-4 py-14 sm:px-5 sm:py-20 lg:px-8"><div className="grid gap-8 lg:grid-cols-2"><div className="rounded-[2rem] bg-stone-950 p-6 text-white shadow-xl sm:p-10"><SectionLabel>Amenities</SectionLabel><h2 className="font-serif text-3xl leading-tight sm:text-5xl">Everything guests need for an easy downtown stay.</h2><p className="mt-4 text-base leading-7 text-stone-200 sm:text-lg">Keep the essentials close: parking, Wi-Fi, pet-friendly rooms, private dining, and on-site hospitality throughout your visit.</p><Button href={HOTEL.contactUrl} className="mt-8">Ask about your stay</Button></div><div className="grid gap-4 sm:grid-cols-2">{["Complimentary Wi-Fi", "Limited complimentary parking", "Pet-friendly accommodation", "Meeting & private dining spaces", "Outdoor guest balcony lounge", "Boutique & Jacuzzi suites"].map((label) => <div key={label} className="rounded-[1.25rem] border border-stone-200 bg-white p-5 shadow-sm"><IconBadge>HS</IconBadge><p className="mt-4 font-medium text-stone-900">{label}</p></div>)}</div></div></section>; }
function Explore() { return <section id="explore" className="bg-amber-50 py-14 sm:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><SectionLabel>Explore</SectionLabel><h2 className="font-serif text-3xl leading-tight sm:text-5xl">Step out into downtown Saskatoon.</h2><p className="mt-4 text-base leading-7 text-stone-600 sm:text-lg">Stay close to shopping, restaurants, nightlife, arts, and riverfront walks.</p><div className="mt-8 rounded-2xl bg-white p-5 shadow-sm"><p className="font-semibold">{HOTEL.address}</p><p className="mt-1 text-sm text-stone-600">In the heart of Downtown Saskatoon.</p></div></div><div className="grid gap-4 sm:grid-cols-3">{["City centre shopping", "Dining & nightlife", "Arts & events", "River walks", "Business district", "Private gatherings"].map((item,i)=><div key={item} className="rounded-[1.5rem] bg-white p-6 shadow-sm"><p className="font-serif text-4xl text-amber-800">0{i+1}</p><p className="mt-5 font-medium">{item}</p></div>)}</div></div></section>; }
function Contact() { return <section id="contact" className="mx-auto max-w-7xl px-4 py-14 sm:px-5 sm:py-20 lg:px-8"><div className="grid overflow-hidden rounded-[2rem] bg-stone-950 shadow-2xl lg:grid-cols-[1.1fr_0.9fr]"><div className="p-6 text-white sm:p-12 lg:p-16"><SectionLabel>Book your stay</SectionLabel><h2 className="font-serif text-3xl leading-tight sm:text-5xl">Ready for downtown Saskatoon?</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-stone-200">Reserve a room, plan a dinner, or ask about private rooms and group stays.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button href={HOTEL.bookingUrl}>Book now</Button><Button href={`mailto:${HOTEL.email}`} variant="outline">Email the hotel</Button></div></div><ContactPanel/></div></section>; }
function ContactPanel() { return <div className="bg-amber-100 p-6 sm:p-12 lg:p-16"><h3 className="font-serif text-3xl">Contact</h3><div className="mt-6 space-y-5 text-stone-800"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-amber-900">Address</p><p className="mt-1">{HOTEL.address}</p></div><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-amber-900">Phone</p><a className="mt-1 block hover:underline" href={phoneHref(HOTEL.phone)}>{HOTEL.phone}</a></div><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-amber-900">Email</p><a className="mt-1 block hover:underline" href={`mailto:${HOTEL.email}`}>{HOTEL.email}</a></div></div></div>; }

function WinstonsPage({ navigate }) { return <DivisionPage id="winstons-top" theme="bg-[#2f241d]" image={IMAGES.winstons} label="Classic English pub connected to The Hotel Senator" title="A warm English pub experience in downtown Saskatoon." body={`${WINSTONS.name} brings together traditional pub character, hearty fare, proper pints on draught, and the cozy atmosphere of a classic English local.`} primary="Explore the pub" cards={pubMenu.map((x)=>[x,"English pub favourite","Pub classic comfort and proper pint energy in a warm downtown local."])} navigate={navigate} />; }
function FlanagansPage({ navigate }) { return <DivisionPage id="flanagans-top" theme="bg-stone-950" image={IMAGES.flanagans} label="Classic steakhouse inside The Hotel Senator" title="Tableside classics, steakhouse charm, and intimate downtown dining." body={`${FLANAGANS.name} brings old-world ambiance, polished service, steaks, seafood, wine, and private dining into the Hotel Senator experience.`} primary="Reserve a table" primaryHref={FLANAGANS.reservationUrl} cards={flanagansExperiences.map(([t,type,key,note])=>[t,type,note,key])} navigate={navigate} />; }
function BreweryPage({ navigate }) { return <DivisionPage id="brewery-top" theme="bg-[#1f1712]" image={IMAGES.brewery} label="Located below Winston's English Pub & Grill" title="The home of great beer in downtown Saskatoon." body={`${BREWERY.name} is a small-batch brewery in the heart of downtown Saskatoon, blending tradition, creativity, and boldness to craft a wide selection of local brews below Winston's English Pub & Grill.`} primary="View the beer lineup" cards={beers.map((x)=>[x,"21st Street pour","Local brew with taproom character from the 21st Street lineup."])} navigate={navigate} brewery />; }
function DivisionPage({ id, theme, image, label, title, body, primary, primaryHref="#details", cards, navigate, brewery }) { const go = (page, section) => (e) => { e.preventDefault(); navigate(page, section); }; return <><section id={id} className={cx("relative overflow-hidden pt-20 text-white sm:pt-24 lg:pt-28", theme)}><div className="relative mx-auto grid max-w-7xl items-center gap-8 px-4 py-10 sm:px-5 sm:py-14 lg:grid-cols-[1.02fr_0.98fr] lg:px-8 lg:py-24"><div><div className="mb-6 inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm text-amber-100 backdrop-blur">{label}</div><h1 className="font-serif text-4xl leading-[0.98] tracking-tight sm:text-6xl lg:text-7xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-stone-200 sm:text-lg">{body}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button href={primaryHref}>{primary}</Button><Button href="#top" onClick={go("hotel","top")} variant="outline">Back to Hotel Senator</Button></div></div><PhotoHero image={image}/></div></section><section id="details" className="mx-auto max-w-7xl px-4 py-14 sm:px-5 sm:py-20 lg:px-8"><div className="mx-auto max-w-3xl text-center"><SectionLabel>{brewery ? "Beer lineup" : "Experience"}</SectionLabel><h2 className="font-serif text-3xl leading-tight sm:text-5xl">{brewery ? "Local brews with range, hops, malt, and rotating taproom character." : "A dedicated page with its own visual identity."}</h2><p className="mt-4 text-base leading-7 text-stone-600 sm:text-lg">Connected to the Hotel Senator site with direct paths to dining, drinks, reservations, and rooms.</p></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{cards.map(([name,type,note,key]) => key ? <PhotoCard key={name} image={IMAGES[key]} title={name} eyebrow={type}><p className="text-sm leading-6 text-stone-600">{note}</p></PhotoCard> : <article key={name} className="rounded-[1.5rem] border border-stone-200 bg-white p-6 shadow-sm"><IconBadge>{brewery ? "21" : "Pub"}</IconBadge><p className="mt-5 text-sm font-semibold uppercase tracking-[0.18em] text-amber-800">{type}</p><h3 className="mt-3 font-serif text-2xl">{name}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{note}</p></article>)}</div></section><Contact/></>; }

export default function HotelSenatorWebsite() {
  const [page, setPage] = useState("hotel");
  const year = useMemo(() => new Date().getFullYear(), []);
  const navigate = (nextPage, sectionId="top") => { setPage(nextPage); window.setTimeout(() => document.getElementById(sectionId)?.scrollIntoView({ behavior:"smooth", block:"start" }), 0); };
  return <main className="min-h-screen bg-stone-50 text-stone-950"><Header page={page} navigate={navigate}/>{page === "brewery" ? <BreweryPage navigate={navigate}/> : page === "winstons" ? <WinstonsPage navigate={navigate}/> : page === "flanagans" ? <FlanagansPage navigate={navigate}/> : <HotelHome navigate={navigate}/>}<footer className="border-t border-stone-200 px-4 py-8 sm:px-5 sm:py-10 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-5 text-sm text-stone-600 md:flex-row md:items-center md:justify-between"><p>© {year} {HOTEL.name}. Concept website design.</p><div className="grid grid-cols-2 gap-3 sm:flex sm:flex-wrap sm:gap-4">{[["Hotel home","hotel","top"],["Winston's Pub","winstons","winstons-top"],["Flanagan's Steakhouse","flanagans","flanagans-top"],["21st Street Brewery","brewery","brewery-top"]].map(([label,p,s])=><a key={label} href={`#${s}`} onClick={(e)=>{e.preventDefault();navigate(p,s)}} className="rounded-full bg-stone-100 px-4 py-2 text-center hover:text-stone-950 sm:bg-transparent sm:px-0 sm:py-0">{label}</a>)}<a href={HOTEL.bookingUrl} className="rounded-full bg-stone-100 px-4 py-2 text-center hover:text-stone-950 sm:bg-transparent sm:px-0 sm:py-0">Book now</a><a href={phoneHref(HOTEL.phone)} className="rounded-full bg-stone-100 px-4 py-2 text-center hover:text-stone-950 sm:bg-transparent sm:px-0 sm:py-0">Call</a></div></div></footer></main>;
}
